[package]
name = "aepc"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
description = "Endfield's Automated Industry Complex inside your terminal"
authors = ["Justin Chen <starryreverie@outlook.com>"]
repository = "https://github.com/StarryReverie/aepc"
readme = "README.md"

[dependencies]
anyhow = "1.0.102"
approx = "0.5"
crossterm = { version = "0.29.0", features = ["event-stream"] }
derive_builder = "0.20.2"
dynosaur = "0.3.0"
futures = "0.3"
getset = "0.1.6"
good_lp = { version = "1.15.0", features = ["microlp"], default-features = false }
ratatui = "0.30.0"
snafu = { version = "0.9.0", features = ["backtrace"] }
tokio = { version = "1.50.0", features = ["sync", "rt", "tokio-macros", "test-util", "macros"] }
unimock = { version = "0.6.8", features = ["mock-tokio-1"] }
